import type { Metadata } from "next";

// Next js gives us a very easy way to import any google font. Syntax is below & font name can be any.
import { Rubik } from "next/font/google";
// We can also use local font.

//import localFont from "next/font/local";

import "./globals.css";

//Components
import Navbar from "./components/Navbar";
import UserContextProvider from '@/app/context/UserContextProvider'


// layout file can be used to put the sections of the website which are on every page(like navbar and footer).



// Creating instance of the font and adding other properties to it (Example)
/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
*/

const rubik = Rubik({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: "Cybertron Support",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body className={`${rubik.className}`}>
          <Navbar />
          {children}
        </body>
      </UserContextProvider>

    </html>
  );
}
